# Generated by Django 4.2.10 on 2024-02-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('reactions_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment_label', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('emotion_label', models.CharField(blank=True, max_length=255, null=True)),
                ('emotion_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
